name: hibis_home
version: 0.1.0
description: Hibis Homepage
environment:
  sdk: '>=2.0.0-dev.50.0 <2.0.0'
dependencies:  
  elements: 1.0.0


dev_dependencies: 
  build_runner: ^0.8.2+2
  build_web_compilers: ^0.3.6